<?php
/**
 * @file mtheme.module
 */

//--------------------------------//
// core Drupal hooks              //
//--------------------------------//

/**
 * Implements hook_help().
 */
function mtheme_help($path, $arg) {
  if ($path == 'admin/help#mtheme') {
    $txt = 'Features Control Panel provides a.... [FINISH HELP TEXT] '; // TODO
    $output = t($txt);
    return $output;
  }
}

/**
 * Implements hook_menu().
 */
function mtheme_menu() {
  $items['admin/structure/mtheme/%/export'] = array(
    'title' => 'export',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mtheme_export_selector', 3),
    'access arguments' => array('mtheme export'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/structure/mtheme/css'] = array(
    'title' => t('Rebuild CSS'),
    'page callback' => 'mtheme_rebuild_css',
    'access arguments' => array('administer mtheme'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/css.inc',
  );
  $items['admin/config/mtheme'] = array(
    'title' => t('Module Theme Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mtheme_admin_settings'),
    //'page callback' => 'mtheme_admin_settings',
    'access arguments' => array('administer mtheme'),
    'file' => 'includes/mtheme.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function mtheme_permission() {
  return array(
    'mtheme export' => array(
      'title' => t('mtheme export'),
      'description' => t('Export CSS selectors.'),
    ),
    'administer mtheme' => array(
      'title' => t('administer mtheme'),
      'description' => t('Create, edit, delete, and enable/disable CSS selectors.'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function mtheme_theme() {
  return array(
    // 'mtheme_selector' => array(
    //   'arguments' => array('element' => NULL),
    // ),
    'mtheme_css_page' => array(
      'variables' => array('css' => NULL),
    ),
  );
}

/**
 * Theme function for admin/build/mtheme/css.
 *
 * @param $variables
 *  - $variables['css']['css'] is a string containing the content of the CSS
 *    file to be written. 
 *  - $variables['css']['name'] is a string containing the machine name of 
 *    the CSS selector being written.
 *
 * @return $output
 *  HTML
 */
function theme_mtheme_css_page($variables) {
  $path = drupal_get_path('module', 'mtheme') . '/mtheme.css';
  drupal_add_css($path);
  $output = "<pre><div class='mtheme-css-page'>" . $variables['css'] . "</div></pre>";

  return $output;
}

/**
 * Implements hook_form_alter().
 *
 * @todo subtheme module stores all these submit, validate,
 *  delete functions in subtheme_ctools_export_ui.inc. I think that's
 *  cleaner because it keeps all the functions related to the same form
 *  in one place. Move this stuff from css.inc to mtheme_ctools_export_ui.inc.
 *  Then, what's left in css.inc should probably be turned into it's own
 *  dedicated css module, for mtheme, subtheme and other modules.
 */
function mtheme_form_alter(&$form, &$form_state, $form_id) {
  // Modify forms for adding and editing mtheme objects
  if ($form_id == 'ctools_export_ui_edit_item_form' && arg(2) == 'mtheme') {
    // admin/build/mtheme/add
    if (arg(3) == 'add' ||
      // admin/build/mtheme/list/selector_name/edit
      (arg(3) == 'list' && ( arg(5) == 'edit' || arg(5) == 'clone' ) )) {
      // Call mtheme functions after new selectors are added or saved.
      $form['#validate'][] = 'mtheme_ctools_export_ui_edit_item_form_validate'; // @TODO validate CSS
      $form['#submit'][] = 'mtheme_ctools_export_ui_edit_item_form_submit';
    }
    // Modify forms for deleting and reverting mtheme objects
  }
  else if ($form_id == 'ctools_export_ui_delete_confirm_form' && arg(2) == 'mtheme') {
    $form['#submit'][] = 'mtheme_ctools_export_ui_delete_confirm_form_submit';
  }
}

//----------------------------------------------//
// mtheme                                       //
//----------------------------------------------//

/**
 * Add mtheme css files.
 *
 * Get all mtheme selectors
 *
 *  $selectors
 *     |
 *     |
 *  +--------------+
 *  |              |
 * disabled    (enabled)
 *                 |
 *        +---------------+
 *        |               |
 *  in code only          |
 *                        |
 *                   in database
 *
 */
function mtheme_init() {
  // If compile is enabled, load the single, compiled stylesheet.
  if (variable_get('mtheme_compile', TRUE)) {
    $stylesheet = mtheme_get_compiled_css();
    $options = mtheme_get_css_options(); 
    drupal_add_css($stylesheet, $options);
  }
  // If compile is not enabled, load each selector's stylesheet individually.
  else {
    // Get selectors from Ctools.
    ctools_include('export');
    $selectors = ctools_export_load_object('mtheme_selector');
    $selectors = (array) $selectors;

    $disabled = array();
    $in_code_only = array();
    $in_database = array();
    foreach ($selectors as $selector) {
      $name = $selector->name;
      if (property_exists($selector, 'disabled') && $selector->disabled) {
        $disabled[] = $name;
      }
      if (property_exists($selector, 'disabled') && $selector->in_code_only) {
        $in_code_only[] = $name;
      }
      if (!in_array($name, $in_code_only)) {
        $in_database[] = $name;
      }
    }

    // Load style sheets in code (features modules).
    $features = features_get_features();
    foreach ($features as $feature) {
      // Make sure the feature module is enabled and has mtheme selectors.
      if (isset($feature->info['features']['mtheme_selector'])) {
        $mtheme_selectors = $feature->info['features']['mtheme_selector']; 
        if ($mtheme_selectors && $feature->status == 1) {
          $module_name = $feature->name;
          // Check each selector.
          foreach ($mtheme_selectors as $name) {
            if (!in_array($name, $disabled) && in_array($name, $in_code_only)) {
              $path = drupal_get_path('module', $module_name);
              $stylesheet = $path . "/mtheme/$name/$name.css"; 
              $options = mtheme_get_css_options(); 
              drupal_add_css($stylesheet, $options);
            } 
          }
        }
      }
    }

    // Load style sheets from files directory (in CSS in database)
    foreach ($in_database as $name) {
      if (!in_array($name, $disabled)) {
        $public = new DrupalPublicStreamWrapper;
        $files_directory = $public->getDirectoryPath();
        $stylesheet = $files_directory . "/mtheme/$name/$name.css";
        $options = mtheme_get_css_options(); 
        drupal_add_css($stylesheet, $options);
      }
    }
  }

}


/**
 * Get the path to compile.css, a single stylesheet including all the 
 * mtheme css selectors.
 * 
 * @param $type
 *  (optional) String. Designate what type of path should be returned.
 *  - 'relative' returns a path relative to Drupal's root directory.
 *  - 'url' returns a URL.
 * 
 * @return $path
 *  String. Relative or absolute path to stylesheet including all mtheme css selectors.
 */
function mtheme_get_compiled_css($type = 'relative') {
  // This is the D7 equivalent of file_directory_path().
  $public = new DrupalPublicStreamWrapper;
  $files_directory = $public->getDirectoryPath();
  // Build relative path.
  $path = $files_directory . '/mtheme/compile/compile.css';
  // Build absolute URL.  
  if ($type == 'url') {
    $path = file_create_url($files_directory);
  }
  return $path;
}

/**
 * @return $options array for drupal_add_css().
 */
function mtheme_get_css_options() {
  return array(
    'group' => CSS_THEME, 
    'every_page' => TRUE, 
    'weight' => 100,
    'type' => 'file',
  );
}

/**
 * Find the path to the mtheme's images directory.
 *
 * If no status is passed, assume we're finding out the
 * current images file location. (If the mtheme is in code only,
 * the images directory lives in a features module. Otherwise, the
 * images directory lives in files/mtheme/images/mtheme_name.)
 * If a status is passed, return the requested path (for an images directory
 * when in code only, or an images directory in the files directory).
 *
 * @param $selector
 *  object, mtheme_selector object.
 *
 * @param $status
 *  string, 'in code only' OR 'files' OR 'mtheme' OR 'compile'
 * 
 *  @todo Replace 'mtheme' status with 'compile', phase out use of 'mtheme'.
 *    In Drupal 6 files/mtheme/mtheme/mtheme.css was used. But Drupal 7 
 *    seems to have problems loading mtheme.css with drupal_add_css(). 
 *    Now the compiled stylesheet lives in files/mtheme/compile/compile.css.
 *
 * @return
 *  string, path/to/images/directory.
 */
function mtheme_images_path($selector = NULL, $status = 'files') {
  $name = $selector->name;

  // Handle 'undefined property' errors.
  if (!property_exists($selector, 'in_code_only')) {
    $selector->in_code_only = FALSE;
  } 
  if ($selector->in_code_only || $status == 'in code only') {
    $feature = mtheme_get_feature($name);
    $module_name = $feature->name;
    $module_path = drupal_get_path('module', $module_name);
    $path = $module_path . "/mtheme/$name/images";
  }
  // Return path to all-images directory in files/mtheme/compile/images.
  else if ($status == 'mtheme' || $status == 'compile') {
    // D6 //$path = file_directory_path() . "/mtheme/mtheme/images";
    // D7 //$path = file_build_uri("/mtheme/compile/images");
    $public = new DrupalPublicStreamWrapper;
    $files_directory = $public->getDirectoryPath();
    $path = $files_directory . "/mtheme/compile/images";
  }
  // Return path to selector-specific images directory in public files directory.
  else if ($status == 'files') {
    // D6 //$path = file_directory_path() . "/mtheme/$name/images";
    // D7 //$path = file_build_uri("/mtheme/$name/images");
    $public = new DrupalPublicStreamWrapper;
    $files_directory = $public->getDirectoryPath();
    $path = $files_directory . "/mtheme/$name/images";
  }

  return $path;
}

/**
 * @param $name
 *  string, mtheme_selector name
 *
 * @return $feature
 *  object, results of features_get_feature($name) for the
 *  feature module that stores the selector requested.
 *
 * @todo cache info about which mtheme is stored in which
 *     module so we don't have to load all these features
 *     modules here?
 */
function mtheme_get_feature($name) {
  $features = features_get_features();
  $feature_with_mtheme = '';

  foreach ($features as $feature) {
    // Check for subthemes.
    if ($feature->info['features']['mtheme_selector']) {
      foreach ($feature->info['features']['mtheme_selector'] as $mtheme_name) {
        if ($mtheme_name == $name) {
          $feature_with_subtheme = $feature;
        }
      }
    }
  }
  return $feature_with_subtheme;
}

/**
 * When an mtheme_selector stored in code is modified through Drupal's GUI
 * copy all the files from the mtheme's features module into the files directory,
 * otherwise relative links to background images will break when
 * the new CSS file is written in the files/mtheme directory. Files should also
 * get copied when an mtheme_selector is cloned.
 *
 * @param $selector
 *  object, mtheme_selector object.
 *
 * @param $paths
 *  array('from' => 'path/to/images', 'to' => 'copy/files/to/here')
 */
function mtheme_copy_files($selector, $paths) {
  $name = $selector->name;
  // Copy images.
  $images_path = $paths['from'];
  $new_images_path = $paths['to'];
  file_prepare_directory($new_images_path, FILE_CREATE_DIRECTORY);
  foreach (@file_scan_directory($images_path, '/.*/') as $file) {
    $source = $file->uri;
    $destination = $new_images_path . "/" . $file->filename;
    file_unmanaged_copy($source, $destination, FILE_EXISTS_REPLACE);
  }
  // return ? // @todo Add error handling. Notify user if unsuccessful?
  // These file functions do a pretty good job notifying
  // administrators about errors,
  // still it seems like there should be something
  // mtheme-specific here.
}

/**
 * @param $names
 *  array, selectors to return. return all if no name is passed.
 *
 * @param $disabled
 *  boolean, return disabled selectors?
 *
 * @return $selectors
 *  array of $selector objects
 */
function mtheme_get_selectors($names = NULL, $disabled = TRUE) {
  $selectors = array();
  if ($names) {
    foreach ($names as $name) {
      $selectors[] = mtheme_selector_load($name);
    }
  }
  else {
    ctools_include('export');
    $selectors = ctools_export_load_object('mtheme_selector');
  }

  return $selectors;
}

/**
 * @param $selectors
 *  array, optionally save mtheme_get_groups the work of calling
 *  ctools_export_load_object.
 *
 * @param $new_selectors
 *  array, optionally include new selectors that have note been saved yet
 *  (this is useful when a new selector is being saved, otherwise Ctools
 *  won't know to load it, and it won't be included in the $groups).
 *
 * @return $groups
 *  array, selectors organized by group
 *
 * $groups[$i]['group_name'] = $group_name
 * $groups[$i]['group_title'] = $group_title;
 * $groups[$i]['selectors'][$selector]
 */
function mtheme_get_groups($selectors = NULL, $new_selectors = NULL) {
  ctools_include('export');
  if (!$selectors) {
    $selectors = ctools_export_load_object('mtheme_selector');
  }
  if ($new_selectors) {
    $selectors = array_merge($new_selectors, $selectors);
  }
  if ($selectors) {
    // Make a unique list of groups;
    foreach ($selectors as $selector) {
      $group_title = $selector->grp;
      $group = strtolower(preg_replace('/[^a-zA-Z0-9-]+/', '-', $group_title));
      $list[$group] = $group_title;
    }
    // Sort group list in alphabetical order by $group_title.
    asort($list);
    // Number groups.
    $groups = array();
    $i = 0;
    foreach ($list as $group => $group_title) {
      $groups[$i]['group_name'] = $group;
      $groups[$i]['group_title'] = $group_title;
      // Organize selectors by group.
      foreach ($selectors as $selector) {
        if ($selector->grp == $group_title) {
          $groups[$i]['selectors'][] = $selector;
        }
      }
      // default, sort alphabetical (handle sort by weight elsewhere)
      sort($groups[$i]['selectors']);
      $i++;
    }

    return $groups;
  }
  else {
    return FALSE;
  }
}

//--------------------------------------------------/
// Ctools plugin                                    /
//--------------------------------------------------/
/**
 * Implmenentation of hook_ctools_plugin_directory.
 */
function mtheme_ctools_plugin_directory($module, $plugin) {
  if ($plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 *
 * Tell CTools that we support the default_mymodule_presets API.
 */
function mtheme_ctools_plugin_api($owner, $api) {
  if ($owner == 'mtheme' && $api == 'default_mtheme_selector') {
    return array('version' => 1);
  }
}

//--------------------------------------------------/
// Ctools export hooks                              /
//--------------------------------------------------/

/**
 * Export a myobj and display it in a form.
 *
 * @param $name
 *  string, unique id for object
 */
function mtheme_export_selector($form, &$form_state, $name) {
  ctools_include('export');
  $obj = mtheme_selector_load($name);
  $title = check_plain($obj->description);
  drupal_set_title($title);
  $code = mtheme_selector_export($obj);
  $lines = substr_count($code, "\n");

  $form['export'] = array(
    '#title' => t('Export data'),
    '#type' => 'textarea',
    '#value' => $code,
    '#rows' => $lines,
    '#description' => t('Copy the export text and paste it into another myobj using the import function.'),
  );
  return $form;
}

/**
 * Load a single myobj.
 */
function mtheme_selector_load($name) {
  ctools_include('export');
  $result = ctools_export_load_object('mtheme_selector', 'names', array($name));
  if (isset($result[$name])) {
    return $result[$name];
  }
}

/**
 * Export a myobj.
 */
function mtheme_selector_export($obj, $indent = '') {
  ctools_include('export');
  $output = ctools_export_object('mtheme_selector', $obj, $indent);
  return $output;
}

/**
 * Save a single myobj.
 */
function mtheme_selector_save(&$myobj) {
  $update = (isset($myobj->sid) && is_numeric($myobj->sid)) ? array('sid') : array();
  return drupal_write_record('mtheme_selector', $myobj, $update);
}



//-------------------------------------------------/
// Features hooks                                  /
//-------------------------------------------------/

/**
 * Implements hook_features_export().
 *
 * Component hook.
 *
 * Add elements to .info file.
 */
function mtheme_selector_features_export($data, &$export, $module_name) {
  // Add dependencies
  // @todo ctools and features dependencies aren't getting added
  //  to info file. I'm not sure it matters, because these are
  //  dependencies of mtheme anyway. Just seems cleaner to include
  //  them.
  //$export['dependencies'][] = "ctools";
  //$export['dependencies'][] = "features";
  $export['dependencies'][] = "mtheme";
  // Add ctools default hook.
  $export['features']['ctools']["mtheme:default_mtheme_selector:1"] = "mtheme:default_mtheme_selector:1";
  // Add mtheme_selector objects
  foreach ($data as $component) {
    $export['features']['mtheme_selector'][$component] = $component;
    // $export['stylesheets']['all'][$component] = $component .'.css';
    // @todo for some reason features components need associative arrays
    // to come out right in the .info file. Stylesheet components
    // seem to need numerical arrays.
    //
    // @todo Stylesheets aren't actually loaded from here. Leave this out of .info files. Revisit this later.
    //$export['stylesheets']['all'][] = "mtheme/$component/$component.css";
  }
  return array();
}

/**
 * Implements hook_features_files().
 *
 * @todo This hook is provided by a patched version of
 * Features. See http://github.com/bhirsch/features.
 */
function mtheme_features_files($export, $module_name) {
  $add_files = array();
  if ($mtheme_selectors = $export['features']['mtheme_selector']) {
    // Get css files for each component.
    $i = 0;
    foreach ($mtheme_selectors as $name) {
      $public = new DrupalPublicStreamWrapper;
      $files_directory = $public->getDirectoryPath();
      $mtheme_path = $files_directory . '/mtheme/' . $name;
      // Get selector's CSS file
      //$add_files[$i]->name = $module_name .'.'. $name;
      $add_files[$i]->name = $name;
      //$add_files[$i]->basename = $module_name .'.'. $name .'.css';
      $add_files[$i]->basename = $name . '.css';
      //$add_files[$i]->filename = $mtheme_path .'/'. $name .'.css';
      $add_files[$i]->filename = $mtheme_path . '/' . $name . '.css';
      //$add_files[$i]->subdir = '';
      $add_files[$i]->subdir = 'mtheme/' . $name;
      // Check for images.
      $selector = mtheme_selector_load($name);
      $images_path = mtheme_images_path($selector);
// @TODO Original below. Coder Update modified this function. Not sure it's right.
// foreach (@file_scan_directory($images_path, '.*') as $file) {
      foreach (@file_scan_directory($images_path, '/.*/') as $file) {
        $i++;
        $add_files[$i]->name = $file->name;
        $add_files[$i]->basename = $file->basename;
        $add_files[$i]->filename = $file->filename;
        $add_files[$i]->subdir = 'mtheme/' . $name . '/images';
      }
      $i++;
    }
  }
  return $add_files;
}

/**
 * Implementation of hook_features_export_render().
 *
 * Component hook.
 */
/*
 function mtheme_selector_features_export_render($module_name, $data, $export = NULL) {
 $render = array();

 // @todo D7 upgrade:
 // Include implementation of hook_enable to re-write CSS.
 // This will not be necessary in D7. mtheme will be able to call
 // hook_modules_enabled() to listen for events like this.
 $code = array();
 $code = '  mtheme_css(); // rewrite files/mtheme/mtheme.css when module is enabled';
 $render['enable'] = $code;

 // @todo D7 upgrade:
 // Include implementation of hook_disable to re-write CSS.
 // This will not be necessary in D7. mtheme will be able to call
 // hook_modules_enabled() to listen for events like this.
 $code = array();
 $code = '  mtheme_css(); // rewrite files/mtheme/mtheme.css when module is enabled';
 $render['disable'] = $code;

 // This writes implementation of hook_default_mtheme_selector just as features/ctools
 // would do if there were no implementation of hook_features_export render here.
 $code = array();
 $code[] = '$export = array();';
 foreach ($data as $name) {
 $selector = mtheme_selector_load($name);
 $code[] = mtheme_selector_export($selector);
 $code[] = "  \$export['{$name}'] = \$selector;";
 }
 $code[] = '  return $export;';
 $code = implode("\n", $code);
 $render['default_mtheme_selector'] = $code;

 return $render;
 }

 //-----------------------------------------------------//
 // Move these functions below into new CSS module      //
 //-----------------------------------------------------//

 /**
 * Begin CSS with timestamp in comment at the top.
 */
function _mtheme_start_css() {
  $time = REQUEST_TIME;
  $date = date("F j, Y, g:i a");
  global $base_url;

  $txt = "Generated $date -- $time -- $base_url";

  $css = '';
  $css .= "/* $txt */ \n \n";

  return $css;
}

/**
 * Write CSS comment for group of selectors.
 */
function _mtheme_group_comment($css = NULL, $group) {
  $txt = t($group['group_title']) . ' ';
  $line = 80 - strlen($txt);
  for ($i = 0; $i < $line; $i++) {
    $txt .= '=';
  }

  $css .= "\n";
  $css .= '/**' . "\n";
  $css .= ' * ' . $txt . "\n";
  $css .= ' */' . "\n";
  $css .= "\n";

  return $css;
}

/**
 * Write CSS for selector.
 *
 * @$css
 *  string, stylesheet being built
 *
 * @$selector
 *  object, mtheme_selector
 *
 * @return
 *  string, $css with selector added to it
 */
function _mtheme_write_selector_css($css = NULL, $selector) {
  // Add comment.
  $css = _mtheme_selector_comment($css, $selector);

  // Add selector and properties.
  if (!property_exists($selector, 'disabled')) {
    $selector->disabled = FALSE; 
  }
  if (!$selector->disabled) {

    // Incase there are multiple selectors, separated by commas and line breaks:
    $selectors = explode("\n", $selector->css_selector);
    foreach ($selectors as $s) {
      $css .= '  ' . $s . "\n";
    }
    $css .= "  {\n";
    $properties = explode("\n", $selector->css_properties);
    foreach ($properties as $property) {
      $css .= "    $property"; // seems like $property hangs onto carriage return
    }
    $css .= "\n  }\n\n";

  }
  else { // selector is disabled
    // Incase there are multiple selectors, separated by commas and line breaks:
    $selectors = explode("\n", $selector->css_selector);
    foreach ($selectors as $s) {
      $css .= '    /* ' . $s . " */\n";
    }
    $txt = t('disabled');
    $css .= "    /* " . $txt . " */ \n\n";

  }

  return $css;
}

/**
 * Write CSS comment for selector.
 *
 * @$css
 *  string, stylesheet being built
 *
 * @$selector
 *  object, mtheme_selector
 *
 * @return
 *  string, $css with comment added to it
 *
 */
function _mtheme_selector_comment($css, $selector) {
  $txt = '';
  $txt = ($selector->title) ? t($selector->title) . ', ' : '';
  $txt .= $selector->name;

  $css .= "  /*** $txt ***/ \n";

  return $css;
}
